### ISSUE TITLE
Cannot install wallet

### ISSUE THREAD

**Issue by Alfa911** [WaykiChain/WaykiChain#16]
Cannot install wallet 
On command `make` i have error : 
"Makefile:1329: *** missing separator.  Stop."

**Comment by tigerich** [comment]
Currently WaykiChain source code supports compilation on Ubuntu 14.04. All the toolchains are tightly dependent to each other. Please make sure you compile the code on Ubuntu 14.04 and have all the dependent software package installed accordingly.

**Comment by Alfa911** [comment]
Now we have 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04

but error have
"Makefile:1329: *** missing separator.  Stop."

We cannot install 14.04 because it very old system

Only 14.04 Ubuntu can use your wallet?

**Comment by tigerich** [comment]
Yeah. For now 14.04 is the only target OS to build our code due to many dependencies only available on that OS. But you could easily install a docker container to run our node. Please refer to another docker project from this repo for steps to run a dockerized node container.

**Comment by dudebing99** [comment]
> Now we have
> Distributor ID: Ubuntu
> Description: Ubuntu 16.04.5 LTS
> Release: 16.04
> 
> but error have
> "Makefile:1329: *** missing separator. Stop."
> 
> We cannot install 14.04 because it very old system
> 
> Only 14.04 Ubuntu can use your wallet?



> Now we have
> Distributor ID: Ubuntu
> Description: Ubuntu 16.04.5 LTS
> Release: 16.04
> 
> but error have
> "Makefile:1329: *** missing separator. Stop."
> 
> We cannot install 14.04 because it very old system
> 
> Only 14.04 Ubuntu can use your wallet?

Ubuntu 16.04.5 LTS is supported now, visit [How to build WaykiChain-core](https://github.com/WaykiChain/WaykiChain/wiki/How-to-build-WaykiChain-core)
