### ISSUE TITLE
Makefile:509: recipe for target 'all-recursive' failed

### ISSUE THREAD

**Issue by ShangXoL** [WaykiChain/WaykiChain#2]
I ran make in the ubuntu16.04 system and found the following error.

Making all in src
make[1]: Entering directory '/mnt/WaykiChain-master/src'
Makefile:1330: *** missing separator.  Stop.
make[1]: Leaving directory '/mnt/WaykiChain-master/src'
Makefile:509: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Do anyone know what's the reason,help me

**Comment by vlyl** [comment]
@ShangXoL 
Maybe you need make it in Ubuntu 1404 system

**Comment by WildSaoFeng** [comment]
我也是和楼主遇到了一样的问题

**Comment by tigerich** [comment]
先提供一个临时解决方案，修改./src/Makefile 找到.PHONY: FORCE的下一行(1318）去掉开头的空格，替换成一个tab键输入，保存后重新编译即可通过。

**Comment by tigerich** [comment]
建议采用我们的容器化部署方式。先关闭此问题
