### ISSUE TITLE
when compile, this problem is show up. how to fix it?

### ISSUE THREAD

**Issue by AlexGobin** [WaykiChain/WaykiChain#255]
make  all-recursive
make[1]: Entering directory '/home/qiulb/blockchain/WaykiChain-release/src'
Making all in .
make[2]: Entering directory '/home/qiulb/blockchain/WaykiChain-release/src'
  CXXLD    coind
libcoin_server.a(init.o): In function `void boost::call_once<void (*)()>(boost::once_flag&, void (*)())':
/usr/local/include/boost/thread/pthread/once.hpp:84: undefined reference to `boost::detail::get_once_per_thread_epoch()'
libcoin_server.a(init.o): In function `boost::pthread::pthread_mutex_scoped_lock::pthread_mutex_scoped_lock(pthread_mutex_t*)':
/usr/local/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:26: undefined reference to `boost::detail::once_epoch_mutex'
libcoin_server.a(init.o): In function `void boost::call_once<void (*)()>(boost::once_flag&, void (*)())':
/usr/local/include/boost/thread/pthread/once.hpp:114: undefined reference to `boost::detail::once_epoch_mutex'
/usr/local/include/boost/thread/pthread/once.hpp:114: undefined reference to `boost::detail::once_epoch_cv'
libcoin_server.a(init.o): In function `boost::pthread::pthread_mutex_scoped_unlock::pthread_mutex_scoped_unlock(pthread_mutex_t*)':
/usr/local/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:51: undefined reference to `boost::detail::once_epoch_mutex'
libcoin_server.a(init.o): In function `boost::pthread::pthread_mutex_scoped_unlock::~pthread_mutex_scoped_unlock()':
/usr/local/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:55: undefined reference to `boost::detail::once_epoch_mutex'
libcoin_server.a(init.o): In function `void boost::call_once<void (*)()>(boost::once_flag&, void (*)())':
/usr/local/include/boost/thread/pthread/once.hpp:107: undefined reference to `boost::detail::once_global_epoch'
/usr/local/include/boost/thread/pthread/once.hpp:108: undefined reference to `boost::detail::once_epoch_cv'
/usr/local/include/boost/thread/pthread/once.hpp:107: undefined reference to `boost::detail::once_global_epoch'
/usr/local/include/boost/thread/pthread/once.hpp:118: undefined reference to `boost::detail::once_global_epoch'
libcoin_server.a(init.o): In function `boost::pthread::pthread_mutex_scoped_lock::unlock()':
/usr/local/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:30: undefined reference to `boost::detail::once_epoch_mutex'
/usr/local/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:30: undefined reference to `boost::detail::once_epoch_mutex'
libcoin_server.a(init.o): In function `boost::pthread::pthread_mutex_scoped_unlock::~pthread_mutex_scoped_unlock()':
/usr/local/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:55: undefined reference to `boost::detail::once_epoch_mutex'
libcoin_server.a(init.o): In function `void boost::call_once<void (*)()>(boost::once_flag&, void (*)())':
/usr/local/include/boost/thread/pthread/once.hpp:103: undefined reference to `boost::detail::once_epoch_cv'
libcoin_wallet.a(walletdb.o): In function `boost::filesystem::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option::enum_type)':
/usr/local/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option::enum_type, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
Makefile:1092: recipe for target 'coind' failed
make[2]: *** [coind] Error 1
make[2]: Leaving directory '/home/qiulb/blockchain/WaykiChain-release/src'
Makefile:1724: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/qiulb/blockchain/WaykiChain-release/src'
Makefile:811: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tigerich** [comment]
Pls follow https://github.com/WaykiChain/WaykiChain/wiki/How-to-build-WaykiChain-core to build your code there
