### ISSUE TITLE
submitsendtx 转账错误，返回错误code -2001

### ISSUE THREAD

**Issue by charliejinc** [WaykiChain/WaykiChain#256]
{"result":null,"error":{"code":-2001,"message":"72260aa2fb4de1dc1824f63ac67b93f348a21291cc54ee594d48273df03ce323"},"id":1}

**Comment by dudebing99** [comment]
> {"result":null,"error":{"code":-2001,"message":"72260aa2fb4de1dc1824f63ac67b93f348a21291cc54ee594d48273df03ce323"},"id":1}

麻烦把对应的请求参数贴一下

**Comment by dudebing99** [comment]
1. dumpwallet xxx.dat
2. 停掉节点，删除目录原有的钱包文件
3. 启动节点，然后倒入钱包 importwallet xxx.dat
