### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [WaykiChain/WaykiChain#260]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [closedb](https://github.com/WaykiChain/WaykiChain/blob/c880afb5ce1cddcdab98b8759e3912169b0b0a56/src/tests/scriptdb_tests.cpp#L35 "closedb function")
- [Shutdown](https://github.com/WaykiChain/WaykiChain/blob/a631577229d570cd36700f12b5198daa50d8264d/src/init.cpp#L163 "Shutdown function")

**Comment by tigerich** [comment]
Thanks for the feedback. But in my view, it is preferred and of a good habit of doing so. There's no extra issue with this while not doing so may result in hitting some potential risks.

**Comment by tigerich** [comment]
Oh. You are correct that C++11 can handle empty pointer deletion nicely.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/WaykiChain/WaykiChain/commit/222d54279a6cc797f582acbcce0ca467cad56340 "Deletion of three unnecessary checks").
