### ISSUE TITLE
分支release 与master的区别有哪些？

### ISSUE THREAD

**Issue by worldmars** [WaykiChain/WaykiChain#263]

**Comment by tigerich** [comment]
- master分支：是主要开发分支，是开发下一个版本的各项功能而提供的；
目前维基链正在开发v3.0版本就是在这个分支上

- release分支：是已经对外发布的，全网节点部署的程序是这个分支编译产生的。
目前维基链对外发布的v2.0就是这个分支构建而来的

（当然如果release分支有bug，会从release分支拉一个小分支如hotfix分支来修改好合并到release分支再对外发布）

上面的都是common sense，开发者必须知道，欢迎早日成为一名合格的开发者、开源开发者，以及区块链开源开发者！

**Comment by worldmars** [comment]
额，看了下master分支目前与release有很多不一样，两个分支多久同步一次？

**Comment by tigerich** [comment]
维基链有龙腾虎跃四大版本规划，目前在开发v3.0『虎』在master分支。而上一个版本v2.0『腾』就是release分支。基本上大半年一个版本的节奏。
