### ISSUE TITLE
Build WaykiChain !

### ISSUE THREAD

**Issue by Gods-good** [WaykiChain/WaykiChain#264]
What is  zhe java pom version ?     1.0.0  is  faild
 <dependency>
            <groupId>com.waykichain.wallet</groupId>
            <artifactId>wicc-wallet-utils</artifactId>
            <version>1.0.0</version>
    </dependency>

**Comment by tigerich** [comment]
You can compile yourself from https://github.com/WaykiChain/wicc-wallet-utils-kotlin

**Comment by Gods-good** [comment]
how can i get last Ledger?   have a java method?
