### ISSUE TITLE
ubuntu16编译3.0.0报错

### ISSUE THREAD

**Issue by gaiyaa** [WaykiChain/WaykiChain#268]
环境没问题，最后一步make报错如下：
`  CXX      entities/libcoin_server_a-key.o
  CXX      entities/libcoin_server_a-keystore.o
  CXX      entities/libcoin_server_a-proposal.o
  CXX      libcoin_server_a-alert.o
  CXX      config/libcoin_server_a-configuration.o
  CXX      crypto/libcoin_server_a-sha256.o
  CXX      libcoin_server_a-init.o
In file included from ./vm/wasm/datastream.hpp:17:0,
                 from ./vm/wasm/wasm_serialize_reflect.hpp:9,
                 from ./vm/wasm/types/inline_transaction.hpp:10,
                 from ./tx/universaltx.h:9,
                 from ./vm/wasm/wasm_context.hpp:10,
                 from ./vm/wasm/modules/wasm_native_dispatch.hpp:4,
                 from init.cpp:61:
./vm/wasm/types/symbol.hpp: In constructor ‘constexpr wasm::symbol_code::symbol_code(std::string_view)’:
./vm/wasm/types/symbol.hpp:123:9: error: call to non-constexpr function ‘std::basic_string_view<_CharT, _Traits>::const_reverse_iterator std::basic_string_view<_CharT, _Traits>::rbegin() const [with _CharT = char; _Traits = std::char_traits<char>; std::basic_string_view<_CharT, _Traits>::const_reverse_iterator = std::reverse_iterator<const char*>]’
         }
         ^
Makefile:9328: recipe for target 'libcoin_server_a-init.o' failed
make[2]: *** [libcoin_server_a-init.o] Error 1
make[2]: Leaving directory '/root/wicc/WaykiChain-3.0.0/src'
Makefile:10684: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/wicc/WaykiChain-3.0.0/src'
Makefile:560: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Comment by tigerich** [comment]
Our current code does not support Ubuntu16.04 and the core team is working on to resolve it.
Meanwhile you may please try it on Ubuntu18.04 which we built our code primarily on without any issues.

**Comment by tigerich** [comment]
Problem solved after we renamed one macro N to NAME to avoid conflict with Boost library internal naming.
