### ISSUE TITLE
节点使用docker怎么从2.0升级到3.0

### ISSUE THREAD

**Issue by zenghq3** [WaykiChain/WaykiChain#269]
之前使用的是docker的wicc/waykicoind:latest版本,现在想升级到3.0,但是发现latest没更新,就使用了wicc/waykicoind:v3.0. 
  然后之前的和现在的数据挂载目录都是/root/.WaykiChain/main.   
  运行wicc/waykicoind:v3.0后报错
`coind: db/version_set.cc:789: leveldb::VersionSet::~VersionSet(): Assertion `dummy_versions_.next_ == &dummy_versions_' failed.`

**Comment by tigerich** [comment]
现在改用了 docker pull wicc/waykicoind:v3.0的方式来更新。我们这边验证一下你这块发现的问题再相应解决。

**Comment by tigerich** [comment]
v3.0节点部署之后，必须重新或者从零块开始拉取数据，而不能在原有数据基础上继续长块，否则就会碰到你上面的问题。

**Comment by zenghq3** [comment]
好的
